### ISSUE TITLE
FAST_PWM_FAN doesn't work

### ISSUE THREAD

**Issue by esenapaj** [MagoKimbra/MarlinKimbra4due#16]
if enable FAST_PWM_FAN in Configuration_Feature.h, it causes compiling error.

error message:
AppData\Local\Temp\build41e4efdcf85178b85a086bd08f467a14.tmp\sketch\module\MK_Main.cpp: In function 'void setPwmFrequency(uint8_t, int)':

AppData\Local\Temp\build41e4efdcf85178b85a086bd08f467a14.tmp\sketch\module\MK_Main.cpp:8609:33: error: 'digitalPinToTimer' was not declared in this scope

     switch(digitalPinToTimer(pin)) {

                                 ^

**Comment by MagoKimbra** [comment]
FAST_PWM_FAN work only 8 bit board...
Now fix bug error...
