### ISSUE TITLE
standard laser machine 

### ISSUE THREAD

**Issue by mkeyno** [MagoKimbra/MarlinKimbra4due#27]
hi @MagoKimbra , thanks  for sharing the codes , however I coud'nt find  active low laser function in your codes , 
actually I made cnc laser with  https://github.com/TurnkeyTyranny modified marlin code  which is now updated with Hanken https://github.com/HakanBastedt/Marlin4Due/tree/Laser for due board , we discus with couple of cool guys about how the most code not consider readiness the tools in codes, and always suppose the tools is up and ready , for example in plasma machine it is necessary  ,the  torch is initiated and ready for cut , also in laser machine , laser power unit always  check the cooling system and power of the beam , and I think  this readiness should be check in loop function , it is standard way which software such as Mach3 do
I really appreciated if you could check those code as well as my due shield for cnc laser and have your comments ,

**Comment by MagoKimbra** [comment]
Ok check and let you know as soon as possible ..

**Comment by mkeyno** [comment]
thanks @MagoKimbra , I've check your codes  also check it with  new code of @HakanBastedt ,he combine his code with TurnkeyTyranny and got fine result , also I suggest define new definition for G0 & G1 code for laser option , because most g-code software generator , don't generate m0 and m5 for laser control 
also can you tell me which software do you use for generating g-code

**Comment by daa5933** [comment]
Mkeyno, I use inkscape with the 305engineering plug-in.  It works well and is simple to use

**Comment by mkeyno** [comment]
hi @daa5933 , I know 305engineering plug-in but it is not very good option for real laser machines , for example if you use the laser for cut thin metal you need dwell time to pierce the material or sometime you need check or command peripheral during the job

**Comment by nextime** [comment]
On standard 8 bit MarlinKimbra i'm proposing a pull request to integrate the laser code from Turnkey Tyranny (https://github.com/MagoKimbra/MarlinKimbra/pull/113), after that, i will move to port the same patch also here for MK4due

**Comment by mkeyno** [comment]
thanks @nextime Franco, I read your repository , it is really awesome to find talented people in Github ,hope  all other participant in this topic can  join the pull

**Comment by mkeyno** [comment]
#https://github.com/MagoKimbra/MarlinKimbra/pull/113#issuecomment-204879376
