### ISSUE TITLE
SERIAL_PORT selection

### ISSUE THREAD

**Issue by Tick007** [MagoKimbra/MarlinKimbra4due#42]
Hi! I've got DUE with dead programming usb port (I mean MEGA16U2 and looks like Rx pin of UART_0). So best Idea is to use one of 3 other UARTS with TTL adapter. But changing SERIAL_PORT in Configuration_basic doesn't affect at all. Because there is no any connection between MSG_PORT in HAL.h and  SERIAL_PORT. So my proposual is just add following in base.h (just before #include "src/HAL/HAL.h"):
#define MSG_PORT  SERIAL_PORT.
If you have better solution please - do it in your way, just make it work. My method - works.

**Comment by MagoKimbra** [comment]
But this version is old.. Look new version MK4duo https://github.com/MagoKimbra/MK4duo
