### ISSUE TITLE
não copila

### ISSUE THREAD

**Issue by Briangsouza** [MagoKimbra/MarlinKimbra4due#7]
Arduino: 1.6.4 (Mac OS X), Placa:"Arduino Duemilanove or Diecimila, ATmega328"

Opções de compilação alteradas, recompilando tudo
In file included from blinkm.cpp:5:0:
base.h:22:22: fatal error: fastio.h: No such file or directory
   #include "fastio.h"
                      ^
compilation terminated.
Erro compilando.

  Este relatório deveria ter mais informações
  "Mostrar saída verbosa durante a compilação"
  habilitado em Arquivo > Preferências.

**Comment by MagoKimbra** [comment]
marlinKimbra4due must be used only on board width arduino due chip...You must use marlinkimbra normal...

Date: Wed, 30 Sep 2015 05:30:08 -0700
